export const ABOUT_DEFAULTS = {
  heroBadgeLabel: "Kurumsal",
  heroTitle: "Sevgi, güven ve modern eğitim yaklaşımı",
  heroSubtitle:
    "Çocukların merakını destekleyen, ailelerle güçlü bağlar kuran bir okul öncesi deneyimi sunuyoruz.",
  aboutBadgeLabel: "Hakkımızda",
  aboutSectionTitle: "Misyonumuz, vizyonumuz ve eğitim anlayışımız",
  aboutSectionSubtitle:
    "Çocukların çok yönlü gelişimini destekleyen, değer odaklı ve bütüncül bir eğitim yaklaşımı benimsiyoruz.",
  missionText:
    "İz Düşümü Anaokulu olarak misyonumuz; çocukların bireysel farklılıklarını gözeterek her birine değer vermek, merak duygularını canlı tutarak öğrenmeye istekli bireyler olmalarını sağlamak ve akademik bilginin yanında değerler eğitimini de ön planda tutmaktır. Güvenli bir öğrenim ortamı oluşturarak çocukların özgüvenlerini geliştirmeyi, oyun yoluyla öğrenmeyi merkeze alarak eğlenceli ve kalıcı öğrenmeler sunmayı hedefliyoruz. Çocuklarda sorumluluk bilinci ve öz disiplin alışkanlığı kazandırmayı, sosyal becerilerini ve iletişim yeteneklerini desteklemeyi önemsiyoruz. Doğa sevgisi ve çevre bilinci kazandırarak; sanat, müzik ve spor gibi alanlarda yeteneklerini keşfetmelerine rehberlik ediyoruz. Milli ve manevi değerlerimizi içselleştirmelerini sağlarken problem çözme ve eleştirel düşünme becerilerini geliştirmeyi amaçlıyoruz. Ailelerimizle iş birliği içerisinde çocuklarımızın gelişimini destekleyen güçlü bir köprü kuruyor, temiz, düzenli ve sağlıklı yaşam bilincini kazandırıyoruz. Teknolojiyi doğru ve bilinçli kullanmayı öğretirken çocuklarımızda hayat boyu öğrenme sevgisi oluşturmayı temel görevimiz olarak görüyoruz.",
  visionText:
    "Vizyonumuz; çocukların gelecekte özgüvenli, üretken ve sorumluluk sahibi bireyler olmalarını sağlamak, hayal güçlerini geliştiren ve özgün fikirler üretebilen bireyler olarak yetişmelerine katkı sunmaktır. Topluma faydalı, manevi değerlerine bağlı, güçlü iletişim kurabilen ve empati sahibi nesiller yetiştirmeyi hedefliyoruz. Doğayı, insanı ve tüm canlıları seven bilinçli bireyler olmalarını desteklerken öğrenmeyi sadece okulda değil hayat boyu sürdürebilecekleri bir alışkanlık haline getirmeyi amaçlıyoruz. Geleceğin bilim insanları, sanatçıları, liderleri ve girişimcileri olabilecek bireyler yetiştirmeyi; çocukların kendi potansiyellerini fark edip en iyi şekilde değerlendirebilmelerini ve karşılaşacakları sorunlara yaratıcı çözümler üretebilmelerini önemsiyoruz. Milli kültürünü bilen ve evrensel değerlere açık bireyler yetiştirerek sağlıklı, mutlu ve huzurlu bir yaşam sürecine katkı sunmayı hedefliyoruz. Her öğrencinin ilgi ve yeteneğine uygun alanlarda başarılı olmasına rehberlik ederek değişen dünyaya uyum sağlayabilen yenilikçi bireyler yetiştiren, geleceğin liderlerini, öğretmenlerini, bilim insanlarını ve sanatçılarını geliştiren öncü bir eğitim kurumu olmayı amaçlıyoruz.",
  educationModelText:
    "Özel İz Düşümü Anaokulu olarak Geleceği Çocuklukla İnşa Ediyoruz anlayışıyla, okulumuzda uygulanan İnşa Erken Çocukluk Programı ile çocuklarımızın merak eden, üreten ve sorumluluk alan bireyler olarak yetişmesini hedefleyen bütüncül bir eğitim modeli sunuyoruz. Daha fazla çocukluk, daha iyi bir gelecek ilkesiyle eğitimi sınıf duvarlarının dışına taşıyarak hayatın merkezine yerleştiriyoruz. Eğitimde fark oluşturan yaklaşımlarımız kapsamında bütüncül gelişimi esas alıyor; 8 kök değer ve 160 günlük özgün içerikle zenginleştirilmiş müfredatımızda erken okuryazarlıktan matematik becerilerine kadar her alanı disiplinler arası bir bağla işliyoruz. Öğrenme sürecini doğa, oyun ve günlük yaşam rutinleriyle harmanlayarak duvarsız eğitim ve oyun anlayışıyla çocukların keşfetme ve düşünme becerilerini destekliyoruz. Değerler ve maneviyat alanında sevgi temelli yaklaşımla ve Kur'an-ı Kerim modülleriyle çocuklarımızın iç dünyasına ve anlam arayışlarına pedagojik bir derinlikle rehberlik ediyoruz. Akademik ve sosyal destek kapsamında ise İnşa Akademi'nin sunduğu profesyonel gelişim programları ve düzenli aile buluşmaları ile okul-aile-öğretmen üçgeninde güçlü bir gelişim ekosistemi kuruyoruz. Böylece çocuklarımızı sadece ilkokula değil; kendine güvenen, değerlerine bağlı ve dünyaya duyarlı bireyler olarak hayata hazırlıyoruz.",
  storyBadgeLabel: "Hikayemiz",
  storyTitle: "2019'dan bugüne sevgiyle büyüyen bir yolculuk",
  storyText:
    "Her çocuğun dünyaya bıraktığı bir iz olduğuna inanıyoruz. İz Düşümü Anaokulu, 2019 yılında çocukların sadece akademik olarak değil; sevgi temelli ve güçlü bir karakterle yetişmesi gerektiği düşüncesiyle kurulmuştur. Eğitim anlayışımızın temelinde, her çocuğun kendine özgü bir gelişim yolculuğu olduğu gerçeği yer alır. Kurulduğumuz günden bu yana amacımız; çocuklarımızın kendilerini güvende hissedecekleri, mutlu olacakları ve potansiyellerini özgürce ortaya koyabilecekleri bir ortam sunmaktır. Bu doğrultuda benimsediğimiz çift kanatlı eğitim modeli ile çocuklarımızın hem akademik gelişimini hem de manevi ve ahlaki değerlerini birlikte destekleyen dengeli bir eğitim yaklaşımı sunuyoruz. Bizim için anaokulu; yalnızca eğitim verilen bir kurum değil, çocukların ilk deneyimlerini yaşadığı, paylaşmayı öğrendiği, özgüven kazandığı ve hayata hazırlandığı, çocuğun kişilik ve karakterinin temellerinin atıldığı özel ve hayatının en önemli yaşam alanıdır. İz Düşümü Anaokulu olarak hedefimiz; merak eden, öğrenmeyi seven, özgüvenli ve değerlerine bağlı bireyler yetiştirmektir. Çocuklarımızın yüzündeki mutluluk ve velilerimizin bize duyduğu güven, en büyük motivasyonumuzdur. Bizler biliyoruz ki geleceğe bırakılan en güzel iz, iyi yetişmiş bir çocuktur.",
  teachersBadgeLabel: "Öğretmen Kadrosu",
  teachersTitle: "Alanında uzman, sevgi dolu ekip",
  teachersSubtitle:
    "Çocukların gelişimini destekleyen güçlü bir rehberlik ve eğitim kadrosu.",
};
